spring:
  datasource:
    url: jdbc:h2:mem:testdb2
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
#Fixme Przy spring security nie działa access do bazy H2 -> Znaleźć odpowiedni wpis w properties/yml i dodać obsługę we filtrze
