spring:

  liquibase:
    change-log: classpath:db/master.xml

  mail:
    host : smtp.gmail.com
    port: 587
    protocol: smtp
  properties:
    mail:
      smtp:
#        auth: true
#        starttls:
#          enable: true