spring:
  datasource:
    url: jdbc:h2:mem:testdb2
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true